#   Ensure the posgresql gem is defined in your Gemfile
#   gem 'pg'

default: &default
  adapter: postgresql
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  timeout: 5000

development:
  <<: *default
  url: "postgresql://<database_user>:<database_password>@localhost:5432/<database_name>"

production:
  <<: *default
  url: <%= ENV['DATABASE_URL'] %>
  