#   Ensure the posgresql gem is defined in your Gemfile
#   gem 'pg'

default: &default
  adapter: postgresql
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  timeout: 5000

development:
  <<: *default
  url: "postgresql://postgres:postgres@localhost:5432/biashara"

test:
  <<: *default
  url: "postgresql://postgres:postgres@localhost:5432/test_biashara"

production:
  <<: *default
  url: <%= ENV['DATABASE_URL'] %>
  